new_globals = {
    'SECONDS': 'seconds',
    'MSEC': 'msec',
    'HOLD': 'hold',
    'BRAKE': 'brake',
    'COAST': 'coast',
    'FORWARD': 'forward',
    'BACKWARD': 'backward',
    'PERCENT': 'percent',
    'REVERSE': 'reverse',
    'AMP': 'amp',
    'VOLT': 'volt',
    'DEGREES': 'degrees',
    'MM': 'mm',
    'RIGHT': 'right',
    'LEFT': 'left',
    'INCHES': 'inches',
}